#!/bin/bash
php7.0 artisan up
php7.0 vendor/bin/phpunit > /dev/null
if [ $? -ne 0 ]; 
then
	echo "failed test"
	exit
else
		git checkout master_tmp
		if [ $? -ne 0 ]; 
		then
			echo "Не могу перейти на ветку master_tmp"
			exit
		else
			php7.0 artisan down
			git pull atlas master
			php7.0 ../.local/bin/composer install
			npm install
			npm run prod

			if [ $? -ne 0 ];
			then
				git checkout master
				php7.0 ../.local/bin/composer install
				npm install
				npm run prod
				php7.0 artisan up
				echo "НЕ УДАЛОСЬ ЗАПУСТИТЬ!!!"
			else
				git checkout master
				git merge master_tmp
				php7.0 artisan up
				echo "УСПЕШНЫЙ DEPLOY"
			fi
		fi
fi
